cmake -S . -B YOUR_BUILD_DIRECTORY -G Ninja \
    -DCEF_ROOT_DIR="../obs-build-dependencies/cef_binary_4638_linux64" \
    -DENABLE_PIPEWIRE=OFF \
    -DENABLE_WAYLAND=OFF \
    -DENABLE_BROWSER=OFF \
    -DENABLE_AJA=0